name: SWE437HW5 Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: clone the test repo
        run: git clone https://github.com/vojtechhabarta/typescript-generator
      - name: open the folder
        run: cd typescript-generator
            ls
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: print the latest commit
        run: git rev-parse HEAD
      - name: compile the module where the test is, and all modules it depends on
        run: mvn test-compile -pl typescript-generator-core -am -e
      - name: run the test to check that it passes
        run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
