name: SWE437HW5 Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - run: git clone https://github.com/vojtechhabarta/typescript-generator
      - run: cd typescript-generator
      - run: ls typescript-generator
      - run: git rev-parse HEAD
      - run: mvn test-compile -pl typescript-generator-core -am -e
      - run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
