name: SWE437HW5 Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - run: git clone https://github.com/GoogleCloudPlatform/DataflowTemplates
      - run: git clone https://github.com/TestingResearchIllinois/NonDex
      - run: ls
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: maven NonDex
        run: mvn install
        working-directory: NonDex
      - name: show all files in the repo
        run: ls
        working-directory: DataflowTemplates
      - name: print the latest commit
        run: git rev-parse HEAD
        working-directory: DataflowTemplates
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: compile the module where the test is, and all modules it depends on
        run: mvn test-compile -pl . -am -e
        working-directory: DataflowTemplates
      - name: run the test to check that it passes
        run: mvn -pl . test -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn
        working-directory: DataflowTemplates
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: if the test passes in regular runs, see if it fails with the NonDex tool that reports flaky tests
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn -DnondexRuns=100 
        working-directory: DataflowTemplates
